# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-29 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(default='后端开发', max_length=20, verbose_name='课程标签'),
        ),
    ]
